package cn.zhouxp.contract.model;

import java.util.Date;

public class Extra {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_extra.extra
     *
     * @mbg.generated
     */
    private byte[] extra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.id
     *
     * @return the value of co_extra.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.id
     *
     * @param id the value for co_extra.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.order_id
     *
     * @return the value of co_extra.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.order_id
     *
     * @param orderId the value for co_extra.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.filename
     *
     * @return the value of co_extra.filename
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.filename
     *
     * @param filename the value for co_extra.filename
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.summary
     *
     * @return the value of co_extra.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.summary
     *
     * @param summary the value for co_extra.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.isdel
     *
     * @return the value of co_extra.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.isdel
     *
     * @param isdel the value for co_extra.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.opid
     *
     * @return the value of co_extra.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.opid
     *
     * @param opid the value for co_extra.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.optime
     *
     * @return the value of co_extra.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.optime
     *
     * @param optime the value for co_extra.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_extra.extra
     *
     * @return the value of co_extra.extra
     *
     * @mbg.generated
     */
    public byte[] getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_extra.extra
     *
     * @param extra the value for co_extra.extra
     *
     * @mbg.generated
     */
    public void setExtra(byte[] extra) {
        this.extra = extra;
    }
}