package cn.zhouxp.contract.model;

public class VContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.cdate
     *
     * @mbg.generated
     */
    private String cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.flower_no
     *
     * @mbg.generated
     */
    private String flowerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.container
     *
     * @mbg.generated
     */
    private String container;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.code_port_id
     *
     * @mbg.generated
     */
    private Long codePortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.code_port_name
     *
     * @mbg.generated
     */
    private Long codePortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.prouct_width_id
     *
     * @mbg.generated
     */
    private Long prouctWidthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.prouct_width_name
     *
     * @mbg.generated
     */
    private Long prouctWidthName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.open_scissors_id
     *
     * @mbg.generated
     */
    private Long openScissorsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.open_scissors_name
     *
     * @mbg.generated
     */
    private Long openScissorsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.product_name
     *
     * @mbg.generated
     */
    private Long productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.technology_id
     *
     * @mbg.generated
     */
    private Long technologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.technology_name
     *
     * @mbg.generated
     */
    private String technologyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.cnumber
     *
     * @mbg.generated
     */
    private Integer cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.packing_id
     *
     * @mbg.generated
     */
    private Long packingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.packing_name
     *
     * @mbg.generated
     */
    private String packingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.sample_name
     *
     * @mbg.generated
     */
    private String sampleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.sample_id
     *
     * @mbg.generated
     */
    private Long sampleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.csample
     *
     * @mbg.generated
     */
    private Integer csample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.grey_weight
     *
     * @mbg.generated
     */
    private Integer greyWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.product_weight
     *
     * @mbg.generated
     */
    private Integer productWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.shipping_mark
     *
     * @mbg.generated
     */
    private String shippingMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.selvage_mark
     *
     * @mbg.generated
     */
    private String selvageMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.isfinish
     *
     * @mbg.generated
     */
    private Boolean isfinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_contract.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.id
     *
     * @return the value of v_contract.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.id
     *
     * @param id the value for v_contract.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.cdate
     *
     * @return the value of v_contract.cdate
     *
     * @mbg.generated
     */
    public String getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.cdate
     *
     * @param cdate the value for v_contract.cdate
     *
     * @mbg.generated
     */
    public void setCdate(String cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.flower_no
     *
     * @return the value of v_contract.flower_no
     *
     * @mbg.generated
     */
    public String getFlowerNo() {
        return flowerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.flower_no
     *
     * @param flowerNo the value for v_contract.flower_no
     *
     * @mbg.generated
     */
    public void setFlowerNo(String flowerNo) {
        this.flowerNo = flowerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.customer_id
     *
     * @return the value of v_contract.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.customer_id
     *
     * @param customerId the value for v_contract.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.customer_name
     *
     * @return the value of v_contract.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.customer_name
     *
     * @param customerName the value for v_contract.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.container
     *
     * @return the value of v_contract.container
     *
     * @mbg.generated
     */
    public String getContainer() {
        return container;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.container
     *
     * @param container the value for v_contract.container
     *
     * @mbg.generated
     */
    public void setContainer(String container) {
        this.container = container;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.code_port_id
     *
     * @return the value of v_contract.code_port_id
     *
     * @mbg.generated
     */
    public Long getCodePortId() {
        return codePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.code_port_id
     *
     * @param codePortId the value for v_contract.code_port_id
     *
     * @mbg.generated
     */
    public void setCodePortId(Long codePortId) {
        this.codePortId = codePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.code_port_name
     *
     * @return the value of v_contract.code_port_name
     *
     * @mbg.generated
     */
    public Long getCodePortName() {
        return codePortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.code_port_name
     *
     * @param codePortName the value for v_contract.code_port_name
     *
     * @mbg.generated
     */
    public void setCodePortName(Long codePortName) {
        this.codePortName = codePortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.prouct_width_id
     *
     * @return the value of v_contract.prouct_width_id
     *
     * @mbg.generated
     */
    public Long getProuctWidthId() {
        return prouctWidthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.prouct_width_id
     *
     * @param prouctWidthId the value for v_contract.prouct_width_id
     *
     * @mbg.generated
     */
    public void setProuctWidthId(Long prouctWidthId) {
        this.prouctWidthId = prouctWidthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.prouct_width_name
     *
     * @return the value of v_contract.prouct_width_name
     *
     * @mbg.generated
     */
    public Long getProuctWidthName() {
        return prouctWidthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.prouct_width_name
     *
     * @param prouctWidthName the value for v_contract.prouct_width_name
     *
     * @mbg.generated
     */
    public void setProuctWidthName(Long prouctWidthName) {
        this.prouctWidthName = prouctWidthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.open_scissors_id
     *
     * @return the value of v_contract.open_scissors_id
     *
     * @mbg.generated
     */
    public Long getOpenScissorsId() {
        return openScissorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.open_scissors_id
     *
     * @param openScissorsId the value for v_contract.open_scissors_id
     *
     * @mbg.generated
     */
    public void setOpenScissorsId(Long openScissorsId) {
        this.openScissorsId = openScissorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.open_scissors_name
     *
     * @return the value of v_contract.open_scissors_name
     *
     * @mbg.generated
     */
    public Long getOpenScissorsName() {
        return openScissorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.open_scissors_name
     *
     * @param openScissorsName the value for v_contract.open_scissors_name
     *
     * @mbg.generated
     */
    public void setOpenScissorsName(Long openScissorsName) {
        this.openScissorsName = openScissorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.product_id
     *
     * @return the value of v_contract.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.product_id
     *
     * @param productId the value for v_contract.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.product_name
     *
     * @return the value of v_contract.product_name
     *
     * @mbg.generated
     */
    public Long getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.product_name
     *
     * @param productName the value for v_contract.product_name
     *
     * @mbg.generated
     */
    public void setProductName(Long productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.technology_id
     *
     * @return the value of v_contract.technology_id
     *
     * @mbg.generated
     */
    public Long getTechnologyId() {
        return technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.technology_id
     *
     * @param technologyId the value for v_contract.technology_id
     *
     * @mbg.generated
     */
    public void setTechnologyId(Long technologyId) {
        this.technologyId = technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.technology_name
     *
     * @return the value of v_contract.technology_name
     *
     * @mbg.generated
     */
    public String getTechnologyName() {
        return technologyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.technology_name
     *
     * @param technologyName the value for v_contract.technology_name
     *
     * @mbg.generated
     */
    public void setTechnologyName(String technologyName) {
        this.technologyName = technologyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.cnumber
     *
     * @return the value of v_contract.cnumber
     *
     * @mbg.generated
     */
    public Integer getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.cnumber
     *
     * @param cnumber the value for v_contract.cnumber
     *
     * @mbg.generated
     */
    public void setCnumber(Integer cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.packing_id
     *
     * @return the value of v_contract.packing_id
     *
     * @mbg.generated
     */
    public Long getPackingId() {
        return packingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.packing_id
     *
     * @param packingId the value for v_contract.packing_id
     *
     * @mbg.generated
     */
    public void setPackingId(Long packingId) {
        this.packingId = packingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.packing_name
     *
     * @return the value of v_contract.packing_name
     *
     * @mbg.generated
     */
    public String getPackingName() {
        return packingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.packing_name
     *
     * @param packingName the value for v_contract.packing_name
     *
     * @mbg.generated
     */
    public void setPackingName(String packingName) {
        this.packingName = packingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.sample_name
     *
     * @return the value of v_contract.sample_name
     *
     * @mbg.generated
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.sample_name
     *
     * @param sampleName the value for v_contract.sample_name
     *
     * @mbg.generated
     */
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.sample_id
     *
     * @return the value of v_contract.sample_id
     *
     * @mbg.generated
     */
    public Long getSampleId() {
        return sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.sample_id
     *
     * @param sampleId the value for v_contract.sample_id
     *
     * @mbg.generated
     */
    public void setSampleId(Long sampleId) {
        this.sampleId = sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.csample
     *
     * @return the value of v_contract.csample
     *
     * @mbg.generated
     */
    public Integer getCsample() {
        return csample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.csample
     *
     * @param csample the value for v_contract.csample
     *
     * @mbg.generated
     */
    public void setCsample(Integer csample) {
        this.csample = csample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.grey_weight
     *
     * @return the value of v_contract.grey_weight
     *
     * @mbg.generated
     */
    public Integer getGreyWeight() {
        return greyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.grey_weight
     *
     * @param greyWeight the value for v_contract.grey_weight
     *
     * @mbg.generated
     */
    public void setGreyWeight(Integer greyWeight) {
        this.greyWeight = greyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.product_weight
     *
     * @return the value of v_contract.product_weight
     *
     * @mbg.generated
     */
    public Integer getProductWeight() {
        return productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.product_weight
     *
     * @param productWeight the value for v_contract.product_weight
     *
     * @mbg.generated
     */
    public void setProductWeight(Integer productWeight) {
        this.productWeight = productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.shipping_mark
     *
     * @return the value of v_contract.shipping_mark
     *
     * @mbg.generated
     */
    public String getShippingMark() {
        return shippingMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.shipping_mark
     *
     * @param shippingMark the value for v_contract.shipping_mark
     *
     * @mbg.generated
     */
    public void setShippingMark(String shippingMark) {
        this.shippingMark = shippingMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.selvage_mark
     *
     * @return the value of v_contract.selvage_mark
     *
     * @mbg.generated
     */
    public String getSelvageMark() {
        return selvageMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.selvage_mark
     *
     * @param selvageMark the value for v_contract.selvage_mark
     *
     * @mbg.generated
     */
    public void setSelvageMark(String selvageMark) {
        this.selvageMark = selvageMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.isfinish
     *
     * @return the value of v_contract.isfinish
     *
     * @mbg.generated
     */
    public Boolean getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.isfinish
     *
     * @param isfinish the value for v_contract.isfinish
     *
     * @mbg.generated
     */
    public void setIsfinish(Boolean isfinish) {
        this.isfinish = isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_contract.remarks
     *
     * @return the value of v_contract.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_contract.remarks
     *
     * @param remarks the value for v_contract.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}