package cn.zhouxp.stock.model;

public class VStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.factory_id
     *
     * @mbg.generated
     */
    private Long factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.factory_name
     *
     * @mbg.generated
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.flower_no
     *
     * @mbg.generated
     */
    private String flowerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.team_id
     *
     * @mbg.generated
     */
    private Long teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.team_name
     *
     * @mbg.generated
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.pa
     *
     * @mbg.generated
     */
    private Integer pa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.ra
     *
     * @mbg.generated
     */
    private Integer ra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.pb
     *
     * @mbg.generated
     */
    private Integer pb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.rb
     *
     * @mbg.generated
     */
    private Integer rb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.p24
     *
     * @mbg.generated
     */
    private Integer p24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.r24
     *
     * @mbg.generated
     */
    private Integer r24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.p119
     *
     * @mbg.generated
     */
    private Integer p119;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.r119
     *
     * @mbg.generated
     */
    private Integer r119;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.premnant
     *
     * @mbg.generated
     */
    private Integer premnant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.rremnant
     *
     * @mbg.generated
     */
    private Integer rremnant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock.isfinish
     *
     * @mbg.generated
     */
    private Boolean isfinish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.id
     *
     * @return the value of v_stock.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.id
     *
     * @param id the value for v_stock.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.order_id
     *
     * @return the value of v_stock.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.order_id
     *
     * @param orderId the value for v_stock.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.factory_id
     *
     * @return the value of v_stock.factory_id
     *
     * @mbg.generated
     */
    public Long getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.factory_id
     *
     * @param factoryId the value for v_stock.factory_id
     *
     * @mbg.generated
     */
    public void setFactoryId(Long factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.factory_name
     *
     * @return the value of v_stock.factory_name
     *
     * @mbg.generated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.factory_name
     *
     * @param factoryName the value for v_stock.factory_name
     *
     * @mbg.generated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.flower_no
     *
     * @return the value of v_stock.flower_no
     *
     * @mbg.generated
     */
    public String getFlowerNo() {
        return flowerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.flower_no
     *
     * @param flowerNo the value for v_stock.flower_no
     *
     * @mbg.generated
     */
    public void setFlowerNo(String flowerNo) {
        this.flowerNo = flowerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.team_id
     *
     * @return the value of v_stock.team_id
     *
     * @mbg.generated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.team_id
     *
     * @param teamId the value for v_stock.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.team_name
     *
     * @return the value of v_stock.team_name
     *
     * @mbg.generated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.team_name
     *
     * @param teamName the value for v_stock.team_name
     *
     * @mbg.generated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.pa
     *
     * @return the value of v_stock.pa
     *
     * @mbg.generated
     */
    public Integer getPa() {
        return pa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.pa
     *
     * @param pa the value for v_stock.pa
     *
     * @mbg.generated
     */
    public void setPa(Integer pa) {
        this.pa = pa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.ra
     *
     * @return the value of v_stock.ra
     *
     * @mbg.generated
     */
    public Integer getRa() {
        return ra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.ra
     *
     * @param ra the value for v_stock.ra
     *
     * @mbg.generated
     */
    public void setRa(Integer ra) {
        this.ra = ra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.pb
     *
     * @return the value of v_stock.pb
     *
     * @mbg.generated
     */
    public Integer getPb() {
        return pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.pb
     *
     * @param pb the value for v_stock.pb
     *
     * @mbg.generated
     */
    public void setPb(Integer pb) {
        this.pb = pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.rb
     *
     * @return the value of v_stock.rb
     *
     * @mbg.generated
     */
    public Integer getRb() {
        return rb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.rb
     *
     * @param rb the value for v_stock.rb
     *
     * @mbg.generated
     */
    public void setRb(Integer rb) {
        this.rb = rb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.p24
     *
     * @return the value of v_stock.p24
     *
     * @mbg.generated
     */
    public Integer getP24() {
        return p24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.p24
     *
     * @param p24 the value for v_stock.p24
     *
     * @mbg.generated
     */
    public void setP24(Integer p24) {
        this.p24 = p24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.r24
     *
     * @return the value of v_stock.r24
     *
     * @mbg.generated
     */
    public Integer getR24() {
        return r24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.r24
     *
     * @param r24 the value for v_stock.r24
     *
     * @mbg.generated
     */
    public void setR24(Integer r24) {
        this.r24 = r24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.p119
     *
     * @return the value of v_stock.p119
     *
     * @mbg.generated
     */
    public Integer getP119() {
        return p119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.p119
     *
     * @param p119 the value for v_stock.p119
     *
     * @mbg.generated
     */
    public void setP119(Integer p119) {
        this.p119 = p119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.r119
     *
     * @return the value of v_stock.r119
     *
     * @mbg.generated
     */
    public Integer getR119() {
        return r119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.r119
     *
     * @param r119 the value for v_stock.r119
     *
     * @mbg.generated
     */
    public void setR119(Integer r119) {
        this.r119 = r119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.premnant
     *
     * @return the value of v_stock.premnant
     *
     * @mbg.generated
     */
    public Integer getPremnant() {
        return premnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.premnant
     *
     * @param premnant the value for v_stock.premnant
     *
     * @mbg.generated
     */
    public void setPremnant(Integer premnant) {
        this.premnant = premnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.rremnant
     *
     * @return the value of v_stock.rremnant
     *
     * @mbg.generated
     */
    public Integer getRremnant() {
        return rremnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.rremnant
     *
     * @param rremnant the value for v_stock.rremnant
     *
     * @mbg.generated
     */
    public void setRremnant(Integer rremnant) {
        this.rremnant = rremnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.remarks
     *
     * @return the value of v_stock.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.remarks
     *
     * @param remarks the value for v_stock.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock.isfinish
     *
     * @return the value of v_stock.isfinish
     *
     * @mbg.generated
     */
    public Boolean getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock.isfinish
     *
     * @param isfinish the value for v_stock.isfinish
     *
     * @mbg.generated
     */
    public void setIsfinish(Boolean isfinish) {
        this.isfinish = isfinish;
    }
}