package cn.zhouxp.stock.model;

public class VStockSum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.container
     *
     * @mbg.generated
     */
    private String container;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.flower_no
     *
     * @mbg.generated
     */
    private String flowerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.factory_id
     *
     * @mbg.generated
     */
    private Long factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.factory_name
     *
     * @mbg.generated
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.pa
     *
     * @mbg.generated
     */
    private Integer pa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.ra
     *
     * @mbg.generated
     */
    private Integer ra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.pb
     *
     * @mbg.generated
     */
    private Integer pb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.rb
     *
     * @mbg.generated
     */
    private Integer rb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.p24
     *
     * @mbg.generated
     */
    private Integer p24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.r24
     *
     * @mbg.generated
     */
    private Integer r24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.p119
     *
     * @mbg.generated
     */
    private Integer p119;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.r119
     *
     * @mbg.generated
     */
    private Integer r119;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.premnant
     *
     * @mbg.generated
     */
    private Integer premnant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.rremnant
     *
     * @mbg.generated
     */
    private Integer rremnant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.ssum
     *
     * @mbg.generated
     */
    private Integer ssum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.tsum
     *
     * @mbg.generated
     */
    private Integer tsum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.prate
     *
     * @mbg.generated
     */
    private Integer prate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.reduce_rate
     *
     * @mbg.generated
     */
    private String reduceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.codelen
     *
     * @mbg.generated
     */
    private Integer codelen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.tr
     *
     * @mbg.generated
     */
    private String tr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.isfinish
     *
     * @mbg.generated
     */
    private Boolean isfinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.ispack
     *
     * @mbg.generated
     */
    private Boolean ispack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.cdate
     *
     * @mbg.generated
     */
    private String cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.ctime
     *
     * @mbg.generated
     */
    private String ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_stock_sum.VERSION
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.id
     *
     * @return the value of v_stock_sum.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.id
     *
     * @param id the value for v_stock_sum.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.order_id
     *
     * @return the value of v_stock_sum.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.order_id
     *
     * @param orderId the value for v_stock_sum.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.container
     *
     * @return the value of v_stock_sum.container
     *
     * @mbg.generated
     */
    public String getContainer() {
        return container;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.container
     *
     * @param container the value for v_stock_sum.container
     *
     * @mbg.generated
     */
    public void setContainer(String container) {
        this.container = container;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.flower_no
     *
     * @return the value of v_stock_sum.flower_no
     *
     * @mbg.generated
     */
    public String getFlowerNo() {
        return flowerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.flower_no
     *
     * @param flowerNo the value for v_stock_sum.flower_no
     *
     * @mbg.generated
     */
    public void setFlowerNo(String flowerNo) {
        this.flowerNo = flowerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.factory_id
     *
     * @return the value of v_stock_sum.factory_id
     *
     * @mbg.generated
     */
    public Long getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.factory_id
     *
     * @param factoryId the value for v_stock_sum.factory_id
     *
     * @mbg.generated
     */
    public void setFactoryId(Long factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.factory_name
     *
     * @return the value of v_stock_sum.factory_name
     *
     * @mbg.generated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.factory_name
     *
     * @param factoryName the value for v_stock_sum.factory_name
     *
     * @mbg.generated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.pa
     *
     * @return the value of v_stock_sum.pa
     *
     * @mbg.generated
     */
    public Integer getPa() {
        return pa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.pa
     *
     * @param pa the value for v_stock_sum.pa
     *
     * @mbg.generated
     */
    public void setPa(Integer pa) {
        this.pa = pa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.ra
     *
     * @return the value of v_stock_sum.ra
     *
     * @mbg.generated
     */
    public Integer getRa() {
        return ra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.ra
     *
     * @param ra the value for v_stock_sum.ra
     *
     * @mbg.generated
     */
    public void setRa(Integer ra) {
        this.ra = ra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.pb
     *
     * @return the value of v_stock_sum.pb
     *
     * @mbg.generated
     */
    public Integer getPb() {
        return pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.pb
     *
     * @param pb the value for v_stock_sum.pb
     *
     * @mbg.generated
     */
    public void setPb(Integer pb) {
        this.pb = pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.rb
     *
     * @return the value of v_stock_sum.rb
     *
     * @mbg.generated
     */
    public Integer getRb() {
        return rb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.rb
     *
     * @param rb the value for v_stock_sum.rb
     *
     * @mbg.generated
     */
    public void setRb(Integer rb) {
        this.rb = rb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.p24
     *
     * @return the value of v_stock_sum.p24
     *
     * @mbg.generated
     */
    public Integer getP24() {
        return p24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.p24
     *
     * @param p24 the value for v_stock_sum.p24
     *
     * @mbg.generated
     */
    public void setP24(Integer p24) {
        this.p24 = p24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.r24
     *
     * @return the value of v_stock_sum.r24
     *
     * @mbg.generated
     */
    public Integer getR24() {
        return r24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.r24
     *
     * @param r24 the value for v_stock_sum.r24
     *
     * @mbg.generated
     */
    public void setR24(Integer r24) {
        this.r24 = r24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.p119
     *
     * @return the value of v_stock_sum.p119
     *
     * @mbg.generated
     */
    public Integer getP119() {
        return p119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.p119
     *
     * @param p119 the value for v_stock_sum.p119
     *
     * @mbg.generated
     */
    public void setP119(Integer p119) {
        this.p119 = p119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.r119
     *
     * @return the value of v_stock_sum.r119
     *
     * @mbg.generated
     */
    public Integer getR119() {
        return r119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.r119
     *
     * @param r119 the value for v_stock_sum.r119
     *
     * @mbg.generated
     */
    public void setR119(Integer r119) {
        this.r119 = r119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.premnant
     *
     * @return the value of v_stock_sum.premnant
     *
     * @mbg.generated
     */
    public Integer getPremnant() {
        return premnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.premnant
     *
     * @param premnant the value for v_stock_sum.premnant
     *
     * @mbg.generated
     */
    public void setPremnant(Integer premnant) {
        this.premnant = premnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.rremnant
     *
     * @return the value of v_stock_sum.rremnant
     *
     * @mbg.generated
     */
    public Integer getRremnant() {
        return rremnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.rremnant
     *
     * @param rremnant the value for v_stock_sum.rremnant
     *
     * @mbg.generated
     */
    public void setRremnant(Integer rremnant) {
        this.rremnant = rremnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.ssum
     *
     * @return the value of v_stock_sum.ssum
     *
     * @mbg.generated
     */
    public Integer getSsum() {
        return ssum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.ssum
     *
     * @param ssum the value for v_stock_sum.ssum
     *
     * @mbg.generated
     */
    public void setSsum(Integer ssum) {
        this.ssum = ssum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.tsum
     *
     * @return the value of v_stock_sum.tsum
     *
     * @mbg.generated
     */
    public Integer getTsum() {
        return tsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.tsum
     *
     * @param tsum the value for v_stock_sum.tsum
     *
     * @mbg.generated
     */
    public void setTsum(Integer tsum) {
        this.tsum = tsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.prate
     *
     * @return the value of v_stock_sum.prate
     *
     * @mbg.generated
     */
    public Integer getPrate() {
        return prate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.prate
     *
     * @param prate the value for v_stock_sum.prate
     *
     * @mbg.generated
     */
    public void setPrate(Integer prate) {
        this.prate = prate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.reduce_rate
     *
     * @return the value of v_stock_sum.reduce_rate
     *
     * @mbg.generated
     */
    public String getReduceRate() {
        return reduceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.reduce_rate
     *
     * @param reduceRate the value for v_stock_sum.reduce_rate
     *
     * @mbg.generated
     */
    public void setReduceRate(String reduceRate) {
        this.reduceRate = reduceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.codelen
     *
     * @return the value of v_stock_sum.codelen
     *
     * @mbg.generated
     */
    public Integer getCodelen() {
        return codelen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.codelen
     *
     * @param codelen the value for v_stock_sum.codelen
     *
     * @mbg.generated
     */
    public void setCodelen(Integer codelen) {
        this.codelen = codelen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.tr
     *
     * @return the value of v_stock_sum.tr
     *
     * @mbg.generated
     */
    public String getTr() {
        return tr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.tr
     *
     * @param tr the value for v_stock_sum.tr
     *
     * @mbg.generated
     */
    public void setTr(String tr) {
        this.tr = tr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.isfinish
     *
     * @return the value of v_stock_sum.isfinish
     *
     * @mbg.generated
     */
    public Boolean getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.isfinish
     *
     * @param isfinish the value for v_stock_sum.isfinish
     *
     * @mbg.generated
     */
    public void setIsfinish(Boolean isfinish) {
        this.isfinish = isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.ispack
     *
     * @return the value of v_stock_sum.ispack
     *
     * @mbg.generated
     */
    public Boolean getIspack() {
        return ispack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.ispack
     *
     * @param ispack the value for v_stock_sum.ispack
     *
     * @mbg.generated
     */
    public void setIspack(Boolean ispack) {
        this.ispack = ispack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.cdate
     *
     * @return the value of v_stock_sum.cdate
     *
     * @mbg.generated
     */
    public String getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.cdate
     *
     * @param cdate the value for v_stock_sum.cdate
     *
     * @mbg.generated
     */
    public void setCdate(String cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.ctime
     *
     * @return the value of v_stock_sum.ctime
     *
     * @mbg.generated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.ctime
     *
     * @param ctime the value for v_stock_sum.ctime
     *
     * @mbg.generated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_stock_sum.VERSION
     *
     * @return the value of v_stock_sum.VERSION
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_stock_sum.VERSION
     *
     * @param version the value for v_stock_sum.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}