package cn.zhouxp.stock.model;

import java.util.ArrayList;
import java.util.List;

public class VStockSumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public VStockSumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andContainerIsNull() {
            addCriterion("container is null");
            return (Criteria) this;
        }

        public Criteria andContainerIsNotNull() {
            addCriterion("container is not null");
            return (Criteria) this;
        }

        public Criteria andContainerEqualTo(String value) {
            addCriterion("container =", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerNotEqualTo(String value) {
            addCriterion("container <>", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerGreaterThan(String value) {
            addCriterion("container >", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerGreaterThanOrEqualTo(String value) {
            addCriterion("container >=", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerLessThan(String value) {
            addCriterion("container <", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerLessThanOrEqualTo(String value) {
            addCriterion("container <=", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerLike(String value) {
            addCriterion("container like", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerNotLike(String value) {
            addCriterion("container not like", value, "container");
            return (Criteria) this;
        }

        public Criteria andContainerIn(List<String> values) {
            addCriterion("container in", values, "container");
            return (Criteria) this;
        }

        public Criteria andContainerNotIn(List<String> values) {
            addCriterion("container not in", values, "container");
            return (Criteria) this;
        }

        public Criteria andContainerBetween(String value1, String value2) {
            addCriterion("container between", value1, value2, "container");
            return (Criteria) this;
        }

        public Criteria andContainerNotBetween(String value1, String value2) {
            addCriterion("container not between", value1, value2, "container");
            return (Criteria) this;
        }

        public Criteria andFlowerNoIsNull() {
            addCriterion("flower_no is null");
            return (Criteria) this;
        }

        public Criteria andFlowerNoIsNotNull() {
            addCriterion("flower_no is not null");
            return (Criteria) this;
        }

        public Criteria andFlowerNoEqualTo(String value) {
            addCriterion("flower_no =", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoNotEqualTo(String value) {
            addCriterion("flower_no <>", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoGreaterThan(String value) {
            addCriterion("flower_no >", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoGreaterThanOrEqualTo(String value) {
            addCriterion("flower_no >=", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoLessThan(String value) {
            addCriterion("flower_no <", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoLessThanOrEqualTo(String value) {
            addCriterion("flower_no <=", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoLike(String value) {
            addCriterion("flower_no like", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoNotLike(String value) {
            addCriterion("flower_no not like", value, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoIn(List<String> values) {
            addCriterion("flower_no in", values, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoNotIn(List<String> values) {
            addCriterion("flower_no not in", values, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoBetween(String value1, String value2) {
            addCriterion("flower_no between", value1, value2, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFlowerNoNotBetween(String value1, String value2) {
            addCriterion("flower_no not between", value1, value2, "flowerNo");
            return (Criteria) this;
        }

        public Criteria andFactoryIdIsNull() {
            addCriterion("factory_id is null");
            return (Criteria) this;
        }

        public Criteria andFactoryIdIsNotNull() {
            addCriterion("factory_id is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryIdEqualTo(Long value) {
            addCriterion("factory_id =", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdNotEqualTo(Long value) {
            addCriterion("factory_id <>", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdGreaterThan(Long value) {
            addCriterion("factory_id >", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("factory_id >=", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdLessThan(Long value) {
            addCriterion("factory_id <", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdLessThanOrEqualTo(Long value) {
            addCriterion("factory_id <=", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdIn(List<Long> values) {
            addCriterion("factory_id in", values, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdNotIn(List<Long> values) {
            addCriterion("factory_id not in", values, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdBetween(Long value1, Long value2) {
            addCriterion("factory_id between", value1, value2, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdNotBetween(Long value1, Long value2) {
            addCriterion("factory_id not between", value1, value2, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIsNull() {
            addCriterion("factory_name is null");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIsNotNull() {
            addCriterion("factory_name is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryNameEqualTo(String value) {
            addCriterion("factory_name =", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotEqualTo(String value) {
            addCriterion("factory_name <>", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameGreaterThan(String value) {
            addCriterion("factory_name >", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("factory_name >=", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLessThan(String value) {
            addCriterion("factory_name <", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLessThanOrEqualTo(String value) {
            addCriterion("factory_name <=", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLike(String value) {
            addCriterion("factory_name like", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotLike(String value) {
            addCriterion("factory_name not like", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIn(List<String> values) {
            addCriterion("factory_name in", values, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotIn(List<String> values) {
            addCriterion("factory_name not in", values, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameBetween(String value1, String value2) {
            addCriterion("factory_name between", value1, value2, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotBetween(String value1, String value2) {
            addCriterion("factory_name not between", value1, value2, "factoryName");
            return (Criteria) this;
        }

        public Criteria andPaIsNull() {
            addCriterion("pa is null");
            return (Criteria) this;
        }

        public Criteria andPaIsNotNull() {
            addCriterion("pa is not null");
            return (Criteria) this;
        }

        public Criteria andPaEqualTo(Integer value) {
            addCriterion("pa =", value, "pa");
            return (Criteria) this;
        }

        public Criteria andPaNotEqualTo(Integer value) {
            addCriterion("pa <>", value, "pa");
            return (Criteria) this;
        }

        public Criteria andPaGreaterThan(Integer value) {
            addCriterion("pa >", value, "pa");
            return (Criteria) this;
        }

        public Criteria andPaGreaterThanOrEqualTo(Integer value) {
            addCriterion("pa >=", value, "pa");
            return (Criteria) this;
        }

        public Criteria andPaLessThan(Integer value) {
            addCriterion("pa <", value, "pa");
            return (Criteria) this;
        }

        public Criteria andPaLessThanOrEqualTo(Integer value) {
            addCriterion("pa <=", value, "pa");
            return (Criteria) this;
        }

        public Criteria andPaIn(List<Integer> values) {
            addCriterion("pa in", values, "pa");
            return (Criteria) this;
        }

        public Criteria andPaNotIn(List<Integer> values) {
            addCriterion("pa not in", values, "pa");
            return (Criteria) this;
        }

        public Criteria andPaBetween(Integer value1, Integer value2) {
            addCriterion("pa between", value1, value2, "pa");
            return (Criteria) this;
        }

        public Criteria andPaNotBetween(Integer value1, Integer value2) {
            addCriterion("pa not between", value1, value2, "pa");
            return (Criteria) this;
        }

        public Criteria andRaIsNull() {
            addCriterion("ra is null");
            return (Criteria) this;
        }

        public Criteria andRaIsNotNull() {
            addCriterion("ra is not null");
            return (Criteria) this;
        }

        public Criteria andRaEqualTo(Integer value) {
            addCriterion("ra =", value, "ra");
            return (Criteria) this;
        }

        public Criteria andRaNotEqualTo(Integer value) {
            addCriterion("ra <>", value, "ra");
            return (Criteria) this;
        }

        public Criteria andRaGreaterThan(Integer value) {
            addCriterion("ra >", value, "ra");
            return (Criteria) this;
        }

        public Criteria andRaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ra >=", value, "ra");
            return (Criteria) this;
        }

        public Criteria andRaLessThan(Integer value) {
            addCriterion("ra <", value, "ra");
            return (Criteria) this;
        }

        public Criteria andRaLessThanOrEqualTo(Integer value) {
            addCriterion("ra <=", value, "ra");
            return (Criteria) this;
        }

        public Criteria andRaIn(List<Integer> values) {
            addCriterion("ra in", values, "ra");
            return (Criteria) this;
        }

        public Criteria andRaNotIn(List<Integer> values) {
            addCriterion("ra not in", values, "ra");
            return (Criteria) this;
        }

        public Criteria andRaBetween(Integer value1, Integer value2) {
            addCriterion("ra between", value1, value2, "ra");
            return (Criteria) this;
        }

        public Criteria andRaNotBetween(Integer value1, Integer value2) {
            addCriterion("ra not between", value1, value2, "ra");
            return (Criteria) this;
        }

        public Criteria andPbIsNull() {
            addCriterion("pb is null");
            return (Criteria) this;
        }

        public Criteria andPbIsNotNull() {
            addCriterion("pb is not null");
            return (Criteria) this;
        }

        public Criteria andPbEqualTo(Integer value) {
            addCriterion("pb =", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotEqualTo(Integer value) {
            addCriterion("pb <>", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThan(Integer value) {
            addCriterion("pb >", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThanOrEqualTo(Integer value) {
            addCriterion("pb >=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThan(Integer value) {
            addCriterion("pb <", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThanOrEqualTo(Integer value) {
            addCriterion("pb <=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbIn(List<Integer> values) {
            addCriterion("pb in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotIn(List<Integer> values) {
            addCriterion("pb not in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbBetween(Integer value1, Integer value2) {
            addCriterion("pb between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotBetween(Integer value1, Integer value2) {
            addCriterion("pb not between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andRbIsNull() {
            addCriterion("rb is null");
            return (Criteria) this;
        }

        public Criteria andRbIsNotNull() {
            addCriterion("rb is not null");
            return (Criteria) this;
        }

        public Criteria andRbEqualTo(Integer value) {
            addCriterion("rb =", value, "rb");
            return (Criteria) this;
        }

        public Criteria andRbNotEqualTo(Integer value) {
            addCriterion("rb <>", value, "rb");
            return (Criteria) this;
        }

        public Criteria andRbGreaterThan(Integer value) {
            addCriterion("rb >", value, "rb");
            return (Criteria) this;
        }

        public Criteria andRbGreaterThanOrEqualTo(Integer value) {
            addCriterion("rb >=", value, "rb");
            return (Criteria) this;
        }

        public Criteria andRbLessThan(Integer value) {
            addCriterion("rb <", value, "rb");
            return (Criteria) this;
        }

        public Criteria andRbLessThanOrEqualTo(Integer value) {
            addCriterion("rb <=", value, "rb");
            return (Criteria) this;
        }

        public Criteria andRbIn(List<Integer> values) {
            addCriterion("rb in", values, "rb");
            return (Criteria) this;
        }

        public Criteria andRbNotIn(List<Integer> values) {
            addCriterion("rb not in", values, "rb");
            return (Criteria) this;
        }

        public Criteria andRbBetween(Integer value1, Integer value2) {
            addCriterion("rb between", value1, value2, "rb");
            return (Criteria) this;
        }

        public Criteria andRbNotBetween(Integer value1, Integer value2) {
            addCriterion("rb not between", value1, value2, "rb");
            return (Criteria) this;
        }

        public Criteria andP24IsNull() {
            addCriterion("p24 is null");
            return (Criteria) this;
        }

        public Criteria andP24IsNotNull() {
            addCriterion("p24 is not null");
            return (Criteria) this;
        }

        public Criteria andP24EqualTo(Integer value) {
            addCriterion("p24 =", value, "p24");
            return (Criteria) this;
        }

        public Criteria andP24NotEqualTo(Integer value) {
            addCriterion("p24 <>", value, "p24");
            return (Criteria) this;
        }

        public Criteria andP24GreaterThan(Integer value) {
            addCriterion("p24 >", value, "p24");
            return (Criteria) this;
        }

        public Criteria andP24GreaterThanOrEqualTo(Integer value) {
            addCriterion("p24 >=", value, "p24");
            return (Criteria) this;
        }

        public Criteria andP24LessThan(Integer value) {
            addCriterion("p24 <", value, "p24");
            return (Criteria) this;
        }

        public Criteria andP24LessThanOrEqualTo(Integer value) {
            addCriterion("p24 <=", value, "p24");
            return (Criteria) this;
        }

        public Criteria andP24In(List<Integer> values) {
            addCriterion("p24 in", values, "p24");
            return (Criteria) this;
        }

        public Criteria andP24NotIn(List<Integer> values) {
            addCriterion("p24 not in", values, "p24");
            return (Criteria) this;
        }

        public Criteria andP24Between(Integer value1, Integer value2) {
            addCriterion("p24 between", value1, value2, "p24");
            return (Criteria) this;
        }

        public Criteria andP24NotBetween(Integer value1, Integer value2) {
            addCriterion("p24 not between", value1, value2, "p24");
            return (Criteria) this;
        }

        public Criteria andR24IsNull() {
            addCriterion("r24 is null");
            return (Criteria) this;
        }

        public Criteria andR24IsNotNull() {
            addCriterion("r24 is not null");
            return (Criteria) this;
        }

        public Criteria andR24EqualTo(Integer value) {
            addCriterion("r24 =", value, "r24");
            return (Criteria) this;
        }

        public Criteria andR24NotEqualTo(Integer value) {
            addCriterion("r24 <>", value, "r24");
            return (Criteria) this;
        }

        public Criteria andR24GreaterThan(Integer value) {
            addCriterion("r24 >", value, "r24");
            return (Criteria) this;
        }

        public Criteria andR24GreaterThanOrEqualTo(Integer value) {
            addCriterion("r24 >=", value, "r24");
            return (Criteria) this;
        }

        public Criteria andR24LessThan(Integer value) {
            addCriterion("r24 <", value, "r24");
            return (Criteria) this;
        }

        public Criteria andR24LessThanOrEqualTo(Integer value) {
            addCriterion("r24 <=", value, "r24");
            return (Criteria) this;
        }

        public Criteria andR24In(List<Integer> values) {
            addCriterion("r24 in", values, "r24");
            return (Criteria) this;
        }

        public Criteria andR24NotIn(List<Integer> values) {
            addCriterion("r24 not in", values, "r24");
            return (Criteria) this;
        }

        public Criteria andR24Between(Integer value1, Integer value2) {
            addCriterion("r24 between", value1, value2, "r24");
            return (Criteria) this;
        }

        public Criteria andR24NotBetween(Integer value1, Integer value2) {
            addCriterion("r24 not between", value1, value2, "r24");
            return (Criteria) this;
        }

        public Criteria andP119IsNull() {
            addCriterion("p119 is null");
            return (Criteria) this;
        }

        public Criteria andP119IsNotNull() {
            addCriterion("p119 is not null");
            return (Criteria) this;
        }

        public Criteria andP119EqualTo(Integer value) {
            addCriterion("p119 =", value, "p119");
            return (Criteria) this;
        }

        public Criteria andP119NotEqualTo(Integer value) {
            addCriterion("p119 <>", value, "p119");
            return (Criteria) this;
        }

        public Criteria andP119GreaterThan(Integer value) {
            addCriterion("p119 >", value, "p119");
            return (Criteria) this;
        }

        public Criteria andP119GreaterThanOrEqualTo(Integer value) {
            addCriterion("p119 >=", value, "p119");
            return (Criteria) this;
        }

        public Criteria andP119LessThan(Integer value) {
            addCriterion("p119 <", value, "p119");
            return (Criteria) this;
        }

        public Criteria andP119LessThanOrEqualTo(Integer value) {
            addCriterion("p119 <=", value, "p119");
            return (Criteria) this;
        }

        public Criteria andP119In(List<Integer> values) {
            addCriterion("p119 in", values, "p119");
            return (Criteria) this;
        }

        public Criteria andP119NotIn(List<Integer> values) {
            addCriterion("p119 not in", values, "p119");
            return (Criteria) this;
        }

        public Criteria andP119Between(Integer value1, Integer value2) {
            addCriterion("p119 between", value1, value2, "p119");
            return (Criteria) this;
        }

        public Criteria andP119NotBetween(Integer value1, Integer value2) {
            addCriterion("p119 not between", value1, value2, "p119");
            return (Criteria) this;
        }

        public Criteria andR119IsNull() {
            addCriterion("r119 is null");
            return (Criteria) this;
        }

        public Criteria andR119IsNotNull() {
            addCriterion("r119 is not null");
            return (Criteria) this;
        }

        public Criteria andR119EqualTo(Integer value) {
            addCriterion("r119 =", value, "r119");
            return (Criteria) this;
        }

        public Criteria andR119NotEqualTo(Integer value) {
            addCriterion("r119 <>", value, "r119");
            return (Criteria) this;
        }

        public Criteria andR119GreaterThan(Integer value) {
            addCriterion("r119 >", value, "r119");
            return (Criteria) this;
        }

        public Criteria andR119GreaterThanOrEqualTo(Integer value) {
            addCriterion("r119 >=", value, "r119");
            return (Criteria) this;
        }

        public Criteria andR119LessThan(Integer value) {
            addCriterion("r119 <", value, "r119");
            return (Criteria) this;
        }

        public Criteria andR119LessThanOrEqualTo(Integer value) {
            addCriterion("r119 <=", value, "r119");
            return (Criteria) this;
        }

        public Criteria andR119In(List<Integer> values) {
            addCriterion("r119 in", values, "r119");
            return (Criteria) this;
        }

        public Criteria andR119NotIn(List<Integer> values) {
            addCriterion("r119 not in", values, "r119");
            return (Criteria) this;
        }

        public Criteria andR119Between(Integer value1, Integer value2) {
            addCriterion("r119 between", value1, value2, "r119");
            return (Criteria) this;
        }

        public Criteria andR119NotBetween(Integer value1, Integer value2) {
            addCriterion("r119 not between", value1, value2, "r119");
            return (Criteria) this;
        }

        public Criteria andPremnantIsNull() {
            addCriterion("premnant is null");
            return (Criteria) this;
        }

        public Criteria andPremnantIsNotNull() {
            addCriterion("premnant is not null");
            return (Criteria) this;
        }

        public Criteria andPremnantEqualTo(Integer value) {
            addCriterion("premnant =", value, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantNotEqualTo(Integer value) {
            addCriterion("premnant <>", value, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantGreaterThan(Integer value) {
            addCriterion("premnant >", value, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantGreaterThanOrEqualTo(Integer value) {
            addCriterion("premnant >=", value, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantLessThan(Integer value) {
            addCriterion("premnant <", value, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantLessThanOrEqualTo(Integer value) {
            addCriterion("premnant <=", value, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantIn(List<Integer> values) {
            addCriterion("premnant in", values, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantNotIn(List<Integer> values) {
            addCriterion("premnant not in", values, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantBetween(Integer value1, Integer value2) {
            addCriterion("premnant between", value1, value2, "premnant");
            return (Criteria) this;
        }

        public Criteria andPremnantNotBetween(Integer value1, Integer value2) {
            addCriterion("premnant not between", value1, value2, "premnant");
            return (Criteria) this;
        }

        public Criteria andRremnantIsNull() {
            addCriterion("rremnant is null");
            return (Criteria) this;
        }

        public Criteria andRremnantIsNotNull() {
            addCriterion("rremnant is not null");
            return (Criteria) this;
        }

        public Criteria andRremnantEqualTo(Integer value) {
            addCriterion("rremnant =", value, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantNotEqualTo(Integer value) {
            addCriterion("rremnant <>", value, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantGreaterThan(Integer value) {
            addCriterion("rremnant >", value, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantGreaterThanOrEqualTo(Integer value) {
            addCriterion("rremnant >=", value, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantLessThan(Integer value) {
            addCriterion("rremnant <", value, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantLessThanOrEqualTo(Integer value) {
            addCriterion("rremnant <=", value, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantIn(List<Integer> values) {
            addCriterion("rremnant in", values, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantNotIn(List<Integer> values) {
            addCriterion("rremnant not in", values, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantBetween(Integer value1, Integer value2) {
            addCriterion("rremnant between", value1, value2, "rremnant");
            return (Criteria) this;
        }

        public Criteria andRremnantNotBetween(Integer value1, Integer value2) {
            addCriterion("rremnant not between", value1, value2, "rremnant");
            return (Criteria) this;
        }

        public Criteria andSsumIsNull() {
            addCriterion("ssum is null");
            return (Criteria) this;
        }

        public Criteria andSsumIsNotNull() {
            addCriterion("ssum is not null");
            return (Criteria) this;
        }

        public Criteria andSsumEqualTo(Integer value) {
            addCriterion("ssum =", value, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumNotEqualTo(Integer value) {
            addCriterion("ssum <>", value, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumGreaterThan(Integer value) {
            addCriterion("ssum >", value, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssum >=", value, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumLessThan(Integer value) {
            addCriterion("ssum <", value, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumLessThanOrEqualTo(Integer value) {
            addCriterion("ssum <=", value, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumIn(List<Integer> values) {
            addCriterion("ssum in", values, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumNotIn(List<Integer> values) {
            addCriterion("ssum not in", values, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumBetween(Integer value1, Integer value2) {
            addCriterion("ssum between", value1, value2, "ssum");
            return (Criteria) this;
        }

        public Criteria andSsumNotBetween(Integer value1, Integer value2) {
            addCriterion("ssum not between", value1, value2, "ssum");
            return (Criteria) this;
        }

        public Criteria andTsumIsNull() {
            addCriterion("tsum is null");
            return (Criteria) this;
        }

        public Criteria andTsumIsNotNull() {
            addCriterion("tsum is not null");
            return (Criteria) this;
        }

        public Criteria andTsumEqualTo(Integer value) {
            addCriterion("tsum =", value, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumNotEqualTo(Integer value) {
            addCriterion("tsum <>", value, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumGreaterThan(Integer value) {
            addCriterion("tsum >", value, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("tsum >=", value, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumLessThan(Integer value) {
            addCriterion("tsum <", value, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumLessThanOrEqualTo(Integer value) {
            addCriterion("tsum <=", value, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumIn(List<Integer> values) {
            addCriterion("tsum in", values, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumNotIn(List<Integer> values) {
            addCriterion("tsum not in", values, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumBetween(Integer value1, Integer value2) {
            addCriterion("tsum between", value1, value2, "tsum");
            return (Criteria) this;
        }

        public Criteria andTsumNotBetween(Integer value1, Integer value2) {
            addCriterion("tsum not between", value1, value2, "tsum");
            return (Criteria) this;
        }

        public Criteria andPrateIsNull() {
            addCriterion("prate is null");
            return (Criteria) this;
        }

        public Criteria andPrateIsNotNull() {
            addCriterion("prate is not null");
            return (Criteria) this;
        }

        public Criteria andPrateEqualTo(Integer value) {
            addCriterion("prate =", value, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateNotEqualTo(Integer value) {
            addCriterion("prate <>", value, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateGreaterThan(Integer value) {
            addCriterion("prate >", value, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateGreaterThanOrEqualTo(Integer value) {
            addCriterion("prate >=", value, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateLessThan(Integer value) {
            addCriterion("prate <", value, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateLessThanOrEqualTo(Integer value) {
            addCriterion("prate <=", value, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateIn(List<Integer> values) {
            addCriterion("prate in", values, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateNotIn(List<Integer> values) {
            addCriterion("prate not in", values, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateBetween(Integer value1, Integer value2) {
            addCriterion("prate between", value1, value2, "prate");
            return (Criteria) this;
        }

        public Criteria andPrateNotBetween(Integer value1, Integer value2) {
            addCriterion("prate not between", value1, value2, "prate");
            return (Criteria) this;
        }

        public Criteria andReduceRateIsNull() {
            addCriterion("reduce_rate is null");
            return (Criteria) this;
        }

        public Criteria andReduceRateIsNotNull() {
            addCriterion("reduce_rate is not null");
            return (Criteria) this;
        }

        public Criteria andReduceRateEqualTo(String value) {
            addCriterion("reduce_rate =", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateNotEqualTo(String value) {
            addCriterion("reduce_rate <>", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateGreaterThan(String value) {
            addCriterion("reduce_rate >", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateGreaterThanOrEqualTo(String value) {
            addCriterion("reduce_rate >=", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateLessThan(String value) {
            addCriterion("reduce_rate <", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateLessThanOrEqualTo(String value) {
            addCriterion("reduce_rate <=", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateLike(String value) {
            addCriterion("reduce_rate like", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateNotLike(String value) {
            addCriterion("reduce_rate not like", value, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateIn(List<String> values) {
            addCriterion("reduce_rate in", values, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateNotIn(List<String> values) {
            addCriterion("reduce_rate not in", values, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateBetween(String value1, String value2) {
            addCriterion("reduce_rate between", value1, value2, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andReduceRateNotBetween(String value1, String value2) {
            addCriterion("reduce_rate not between", value1, value2, "reduceRate");
            return (Criteria) this;
        }

        public Criteria andCodelenIsNull() {
            addCriterion("codelen is null");
            return (Criteria) this;
        }

        public Criteria andCodelenIsNotNull() {
            addCriterion("codelen is not null");
            return (Criteria) this;
        }

        public Criteria andCodelenEqualTo(Integer value) {
            addCriterion("codelen =", value, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenNotEqualTo(Integer value) {
            addCriterion("codelen <>", value, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenGreaterThan(Integer value) {
            addCriterion("codelen >", value, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenGreaterThanOrEqualTo(Integer value) {
            addCriterion("codelen >=", value, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenLessThan(Integer value) {
            addCriterion("codelen <", value, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenLessThanOrEqualTo(Integer value) {
            addCriterion("codelen <=", value, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenIn(List<Integer> values) {
            addCriterion("codelen in", values, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenNotIn(List<Integer> values) {
            addCriterion("codelen not in", values, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenBetween(Integer value1, Integer value2) {
            addCriterion("codelen between", value1, value2, "codelen");
            return (Criteria) this;
        }

        public Criteria andCodelenNotBetween(Integer value1, Integer value2) {
            addCriterion("codelen not between", value1, value2, "codelen");
            return (Criteria) this;
        }

        public Criteria andTrIsNull() {
            addCriterion("tr is null");
            return (Criteria) this;
        }

        public Criteria andTrIsNotNull() {
            addCriterion("tr is not null");
            return (Criteria) this;
        }

        public Criteria andTrEqualTo(String value) {
            addCriterion("tr =", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrNotEqualTo(String value) {
            addCriterion("tr <>", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrGreaterThan(String value) {
            addCriterion("tr >", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrGreaterThanOrEqualTo(String value) {
            addCriterion("tr >=", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrLessThan(String value) {
            addCriterion("tr <", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrLessThanOrEqualTo(String value) {
            addCriterion("tr <=", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrLike(String value) {
            addCriterion("tr like", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrNotLike(String value) {
            addCriterion("tr not like", value, "tr");
            return (Criteria) this;
        }

        public Criteria andTrIn(List<String> values) {
            addCriterion("tr in", values, "tr");
            return (Criteria) this;
        }

        public Criteria andTrNotIn(List<String> values) {
            addCriterion("tr not in", values, "tr");
            return (Criteria) this;
        }

        public Criteria andTrBetween(String value1, String value2) {
            addCriterion("tr between", value1, value2, "tr");
            return (Criteria) this;
        }

        public Criteria andTrNotBetween(String value1, String value2) {
            addCriterion("tr not between", value1, value2, "tr");
            return (Criteria) this;
        }

        public Criteria andIsfinishIsNull() {
            addCriterion("isfinish is null");
            return (Criteria) this;
        }

        public Criteria andIsfinishIsNotNull() {
            addCriterion("isfinish is not null");
            return (Criteria) this;
        }

        public Criteria andIsfinishEqualTo(Boolean value) {
            addCriterion("isfinish =", value, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishNotEqualTo(Boolean value) {
            addCriterion("isfinish <>", value, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishGreaterThan(Boolean value) {
            addCriterion("isfinish >", value, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isfinish >=", value, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishLessThan(Boolean value) {
            addCriterion("isfinish <", value, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishLessThanOrEqualTo(Boolean value) {
            addCriterion("isfinish <=", value, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishIn(List<Boolean> values) {
            addCriterion("isfinish in", values, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishNotIn(List<Boolean> values) {
            addCriterion("isfinish not in", values, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishBetween(Boolean value1, Boolean value2) {
            addCriterion("isfinish between", value1, value2, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIsfinishNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isfinish not between", value1, value2, "isfinish");
            return (Criteria) this;
        }

        public Criteria andIspackIsNull() {
            addCriterion("ispack is null");
            return (Criteria) this;
        }

        public Criteria andIspackIsNotNull() {
            addCriterion("ispack is not null");
            return (Criteria) this;
        }

        public Criteria andIspackEqualTo(Boolean value) {
            addCriterion("ispack =", value, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackNotEqualTo(Boolean value) {
            addCriterion("ispack <>", value, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackGreaterThan(Boolean value) {
            addCriterion("ispack >", value, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ispack >=", value, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackLessThan(Boolean value) {
            addCriterion("ispack <", value, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackLessThanOrEqualTo(Boolean value) {
            addCriterion("ispack <=", value, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackIn(List<Boolean> values) {
            addCriterion("ispack in", values, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackNotIn(List<Boolean> values) {
            addCriterion("ispack not in", values, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackBetween(Boolean value1, Boolean value2) {
            addCriterion("ispack between", value1, value2, "ispack");
            return (Criteria) this;
        }

        public Criteria andIspackNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ispack not between", value1, value2, "ispack");
            return (Criteria) this;
        }

        public Criteria andCdateIsNull() {
            addCriterion("cdate is null");
            return (Criteria) this;
        }

        public Criteria andCdateIsNotNull() {
            addCriterion("cdate is not null");
            return (Criteria) this;
        }

        public Criteria andCdateEqualTo(String value) {
            addCriterion("cdate =", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateNotEqualTo(String value) {
            addCriterion("cdate <>", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateGreaterThan(String value) {
            addCriterion("cdate >", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateGreaterThanOrEqualTo(String value) {
            addCriterion("cdate >=", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateLessThan(String value) {
            addCriterion("cdate <", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateLessThanOrEqualTo(String value) {
            addCriterion("cdate <=", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateLike(String value) {
            addCriterion("cdate like", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateNotLike(String value) {
            addCriterion("cdate not like", value, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateIn(List<String> values) {
            addCriterion("cdate in", values, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateNotIn(List<String> values) {
            addCriterion("cdate not in", values, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateBetween(String value1, String value2) {
            addCriterion("cdate between", value1, value2, "cdate");
            return (Criteria) this;
        }

        public Criteria andCdateNotBetween(String value1, String value2) {
            addCriterion("cdate not between", value1, value2, "cdate");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(String value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(String value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(String value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(String value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(String value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLike(String value) {
            addCriterion("ctime like", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotLike(String value) {
            addCriterion("ctime not like", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<String> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<String> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(String value1, String value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(String value1, String value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_stock_sum
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_stock_sum
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}