package cn.zhouxp.customer.model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.linkname
     *
     * @mbg.generated
     */
    private String linkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.categroy_id
     *
     * @mbg.generated
     */
    private Long categroyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_customer.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.id
     *
     * @return the value of c_customer.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.id
     *
     * @param id the value for c_customer.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.cname
     *
     * @return the value of c_customer.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.cname
     *
     * @param cname the value for c_customer.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.linkname
     *
     * @return the value of c_customer.linkname
     *
     * @mbg.generated
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.linkname
     *
     * @param linkname the value for c_customer.linkname
     *
     * @mbg.generated
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.phone
     *
     * @return the value of c_customer.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.phone
     *
     * @param phone the value for c_customer.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.categroy_id
     *
     * @return the value of c_customer.categroy_id
     *
     * @mbg.generated
     */
    public Long getCategroyId() {
        return categroyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.categroy_id
     *
     * @param categroyId the value for c_customer.categroy_id
     *
     * @mbg.generated
     */
    public void setCategroyId(Long categroyId) {
        this.categroyId = categroyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.isdel
     *
     * @return the value of c_customer.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.isdel
     *
     * @param isdel the value for c_customer.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.remarks
     *
     * @return the value of c_customer.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.remarks
     *
     * @param remarks the value for c_customer.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.opid
     *
     * @return the value of c_customer.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.opid
     *
     * @param opid the value for c_customer.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.optime
     *
     * @return the value of c_customer.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.optime
     *
     * @param optime the value for c_customer.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}