package cn.zhouxp.base.model;

import java.util.Date;

public class CodePort {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_code_port.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_code_port.code_port
     *
     * @mbg.generated
     */
    private Integer codePort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_code_port.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_code_port.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_code_port.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_code_port.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_code_port.id
     *
     * @return the value of b_code_port.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_code_port.id
     *
     * @param id the value for b_code_port.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_code_port.code_port
     *
     * @return the value of b_code_port.code_port
     *
     * @mbg.generated
     */
    public Integer getCodePort() {
        return codePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_code_port.code_port
     *
     * @param codePort the value for b_code_port.code_port
     *
     * @mbg.generated
     */
    public void setCodePort(Integer codePort) {
        this.codePort = codePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_code_port.isdel
     *
     * @return the value of b_code_port.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_code_port.isdel
     *
     * @param isdel the value for b_code_port.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_code_port.remarks
     *
     * @return the value of b_code_port.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_code_port.remarks
     *
     * @param remarks the value for b_code_port.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_code_port.opid
     *
     * @return the value of b_code_port.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_code_port.opid
     *
     * @param opid the value for b_code_port.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_code_port.optime
     *
     * @return the value of b_code_port.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_code_port.optime
     *
     * @param optime the value for b_code_port.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}