package cn.zhouxp.base.model;

import java.util.Date;

public class OpenScissors {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_open_scissors.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_open_scissors.open_scissors
     *
     * @mbg.generated
     */
    private Integer openScissors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_open_scissors.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_open_scissors.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_open_scissors.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_open_scissors.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_open_scissors.id
     *
     * @return the value of b_open_scissors.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_open_scissors.id
     *
     * @param id the value for b_open_scissors.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_open_scissors.open_scissors
     *
     * @return the value of b_open_scissors.open_scissors
     *
     * @mbg.generated
     */
    public Integer getOpenScissors() {
        return openScissors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_open_scissors.open_scissors
     *
     * @param openScissors the value for b_open_scissors.open_scissors
     *
     * @mbg.generated
     */
    public void setOpenScissors(Integer openScissors) {
        this.openScissors = openScissors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_open_scissors.isdel
     *
     * @return the value of b_open_scissors.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_open_scissors.isdel
     *
     * @param isdel the value for b_open_scissors.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_open_scissors.remarks
     *
     * @return the value of b_open_scissors.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_open_scissors.remarks
     *
     * @param remarks the value for b_open_scissors.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_open_scissors.opid
     *
     * @return the value of b_open_scissors.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_open_scissors.opid
     *
     * @param opid the value for b_open_scissors.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_open_scissors.optime
     *
     * @return the value of b_open_scissors.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_open_scissors.optime
     *
     * @param optime the value for b_open_scissors.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}