package cn.zhouxp.base.model;

import java.util.Date;

public class PrintingFactory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.ccode
     *
     * @mbg.generated
     */
    private Integer ccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.printing_factory
     *
     * @mbg.generated
     */
    private String printingFactory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_printing_factory.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.id
     *
     * @return the value of b_printing_factory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.id
     *
     * @param id the value for b_printing_factory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.ccode
     *
     * @return the value of b_printing_factory.ccode
     *
     * @mbg.generated
     */
    public Integer getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.ccode
     *
     * @param ccode the value for b_printing_factory.ccode
     *
     * @mbg.generated
     */
    public void setCcode(Integer ccode) {
        this.ccode = ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.printing_factory
     *
     * @return the value of b_printing_factory.printing_factory
     *
     * @mbg.generated
     */
    public String getPrintingFactory() {
        return printingFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.printing_factory
     *
     * @param printingFactory the value for b_printing_factory.printing_factory
     *
     * @mbg.generated
     */
    public void setPrintingFactory(String printingFactory) {
        this.printingFactory = printingFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.isdel
     *
     * @return the value of b_printing_factory.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.isdel
     *
     * @param isdel the value for b_printing_factory.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.remarks
     *
     * @return the value of b_printing_factory.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.remarks
     *
     * @param remarks the value for b_printing_factory.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.opid
     *
     * @return the value of b_printing_factory.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.opid
     *
     * @param opid the value for b_printing_factory.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_printing_factory.optime
     *
     * @return the value of b_printing_factory.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_printing_factory.optime
     *
     * @param optime the value for b_printing_factory.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}