package cn.zhouxp.base.model;

import java.util.Date;

public class ProductWidth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_width.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_width.product_width
     *
     * @mbg.generated
     */
    private Integer productWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_width.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_width.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_width.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_width.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_width.id
     *
     * @return the value of b_product_width.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_width.id
     *
     * @param id the value for b_product_width.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_width.product_width
     *
     * @return the value of b_product_width.product_width
     *
     * @mbg.generated
     */
    public Integer getProductWidth() {
        return productWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_width.product_width
     *
     * @param productWidth the value for b_product_width.product_width
     *
     * @mbg.generated
     */
    public void setProductWidth(Integer productWidth) {
        this.productWidth = productWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_width.isdel
     *
     * @return the value of b_product_width.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_width.isdel
     *
     * @param isdel the value for b_product_width.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_width.remarks
     *
     * @return the value of b_product_width.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_width.remarks
     *
     * @param remarks the value for b_product_width.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_width.opid
     *
     * @return the value of b_product_width.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_width.opid
     *
     * @param opid the value for b_product_width.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_width.optime
     *
     * @return the value of b_product_width.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_width.optime
     *
     * @param optime the value for b_product_width.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}