package cn.zhouxp.base.model;

import java.util.Date;

public class Simple {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.clength
     *
     * @mbg.generated
     */
    private Integer clength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_simple.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.id
     *
     * @return the value of b_simple.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.id
     *
     * @param id the value for b_simple.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.cname
     *
     * @return the value of b_simple.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.cname
     *
     * @param cname the value for b_simple.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.clength
     *
     * @return the value of b_simple.clength
     *
     * @mbg.generated
     */
    public Integer getClength() {
        return clength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.clength
     *
     * @param clength the value for b_simple.clength
     *
     * @mbg.generated
     */
    public void setClength(Integer clength) {
        this.clength = clength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.isdel
     *
     * @return the value of b_simple.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.isdel
     *
     * @param isdel the value for b_simple.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.remarks
     *
     * @return the value of b_simple.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.remarks
     *
     * @param remarks the value for b_simple.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.opid
     *
     * @return the value of b_simple.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.opid
     *
     * @param opid the value for b_simple.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_simple.optime
     *
     * @return the value of b_simple.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_simple.optime
     *
     * @param optime the value for b_simple.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}