package cn.zhouxp.base.model;

public class TeamGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_team_group.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_team_group.team_id
     *
     * @mbg.generated
     */
    private Long teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_team_group.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_team_group.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_team_group.isleader
     *
     * @mbg.generated
     */
    private Boolean isleader;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_team_group.id
     *
     * @return the value of b_team_group.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_team_group.id
     *
     * @param id the value for b_team_group.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_team_group.team_id
     *
     * @return the value of b_team_group.team_id
     *
     * @mbg.generated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_team_group.team_id
     *
     * @param teamId the value for b_team_group.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_team_group.user_id
     *
     * @return the value of b_team_group.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_team_group.user_id
     *
     * @param userId the value for b_team_group.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_team_group.cname
     *
     * @return the value of b_team_group.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_team_group.cname
     *
     * @param cname the value for b_team_group.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_team_group.isleader
     *
     * @return the value of b_team_group.isleader
     *
     * @mbg.generated
     */
    public Boolean getIsleader() {
        return isleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_team_group.isleader
     *
     * @param isleader the value for b_team_group.isleader
     *
     * @mbg.generated
     */
    public void setIsleader(Boolean isleader) {
        this.isleader = isleader;
    }
}