package cn.zhouxp.base.model;

import java.util.Date;

public class Technology {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_technology.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_technology.technology
     *
     * @mbg.generated
     */
    private String technology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_technology.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_technology.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_technology.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_technology.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_technology.id
     *
     * @return the value of b_technology.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_technology.id
     *
     * @param id the value for b_technology.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_technology.technology
     *
     * @return the value of b_technology.technology
     *
     * @mbg.generated
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_technology.technology
     *
     * @param technology the value for b_technology.technology
     *
     * @mbg.generated
     */
    public void setTechnology(String technology) {
        this.technology = technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_technology.isdel
     *
     * @return the value of b_technology.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_technology.isdel
     *
     * @param isdel the value for b_technology.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_technology.remarks
     *
     * @return the value of b_technology.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_technology.remarks
     *
     * @param remarks the value for b_technology.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_technology.opid
     *
     * @return the value of b_technology.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_technology.opid
     *
     * @param opid the value for b_technology.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_technology.optime
     *
     * @return the value of b_technology.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_technology.optime
     *
     * @param optime the value for b_technology.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}